stages:
- test
- deploy
language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: pip install tox
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
- npm install
- npm run build
deploy:
  stage: deploy
  skip_cleanup: true
  before_script: npm install && npm run build
  provider: pypi
  on:
    tags: true
  distributions: sdist bdist_wheel
  user: osherdp
  password:
    secure: rlEMI6ZNtOcVD7waAKH111lwBkitTtXoT2nCtn9WcATxqOHrRLmI8mPm41QKSKy8qc6+sKLckyXaT951w6eNKjdP3DA+lDPyugzORfqoNeWO5oKOwmIfBLn49NoZ2xAeSL/EUlNtQsOLvdzW7uPdVZNKOBo1rR11ZrBQH12k1iBaHbbnOnnM+Pg2vSCI5mQvP/zrbaOsA6w3Wl0EYW6lJBtjZa3rrniLcU4RBLz6KDKvNxDXE3Gat/d/zZ8LfDrUaZwXYb+eGAu6wpqJmyTUzRkJHV+UlrxHQnZpHJKZSyGSAYAYIL3Gej4P3nxUx9QWeeqKgpO9N0p9l+C3yxQU9Nh7P4L3WpKQmimF87q0EPFi5SSi3zB1JZ/sIqFBMVXKIeBZuBZPAD667DAOqBcFo4LurGcfAAH468oQLbU/HBQRxMsJNsf1kSUrIK1rlzRFXXzyQ2cxvM8arwhX6Xrq1dKmDhKC3oaNxlMxO+3iTJVvRN9TmiSm8kuPSbAjINC8uc8UKJ80V6OTC7prlGwAwsNB2RDazX8bNch3ozWCjFRLRtd2XTmG/YX0YBtCQu7ynq+TQTQsnnZyAP+1rOYkujexNDfLvm02bCMDyb5mnL2geFcvjTVL8uw3WL+JSdcnhVpoAiKGa7IubWZIUXUo6RjK30eqGyn6whT+gR6faPg=
