stages:
- test
- name: deploy
  if: tag IS present

language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: pip install tox
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
- npm install
- npm run build

jobs:
  include:
    - stage: deploy
      python: "3.6"
      script: skip
      deploy:
        stage: deploy
        skip_cleanup: true
        provider: pypi
        on:
          tags: true
        distributions: sdist bdist_wheel
        user: osherdp
        password:
          secure: fc4/fMgl809z3BD2E9M8WgKHXSu6ZlB8oG7V2SUOKCWyNDo0o+48mGEUrt0E9MfGheik4dZrbJuLAAPHortnTW4q91qrvqIXLQ8cuIY7qhZOFz+GAgyRqXztjo+ltn3Wbo374+Z048JUAVjiCcHQIoaMZihVSL5b5ZGGx1f9EwZi6w0yROxuvgfkh/a3anN+001eF+Q5rc7YeLlfXWwFUdOa9i66mmzSqD3FkZygw7bvUnnqHSpraK1utmY567EBPQ0d7MV9wAiTkeV8sxkpjGitjxOATs3gFS3UREgCtyeDQA8ihLhxpS/1FdavcTo/eoGyevFEzJVW17sfD7NfxI76Kx/7VB+ZS7WiDiBdpYRjd12tEs98Q6r6pILUU1ozv+RTxBkzP4occErPJ2HcLGxcrqwy0gVTulLXhwSBODPGbIOcspj78zbrqDp5/m9oX8RKQRkHYtZOAJn5SJp2YbNM3KHn67ZDG7vrz9hhWNrTwhjz3GgP45U44BjRQXaFRBvF/jT/jxVRw2VymdcMeJCjlMefWFuSn5M/yW2j2E3GpSo3waU0mHxQ3+AEX6E/bHqPlygzY+zJw+4IzQQJrn4yK0/NK78oYsyN0vDIfLWHhiwEp4GqYW547OFFmCCAySpXFBSLEul5aokySSciVRf2eXHzt5xMsFErqAry59M=
